#!/bin/sh -l
# FILENAME:  sjob1

#SBATCH -p a100-80gb
#SBATCH --mem 32G
#SBATCH -n32
#SBATCH -A stanchan
#SBATCH --nodes=1 --gpus-per-node=1 
#SBATCH --time=4-00:00:00
#SBATCH --job-name ex_3


cd ../..
conda activate mypackages
accelerate launch trainer.py -opt ./checkpoints/ICASSP_26/ex3.yml