# Flux2 Klein LoRA deblurring (non-JEPA).
name: Motion
model_type: Flux2KleinLoRA_model
is_train: true
report_to: [comet_ml, tensorboard]
push_to_hub: false
num_gpu: 1
seed: 42
mixed_precision: bf16
allow_tf32: true

pretrained_model_name_or_path: black-forest-labs/FLUX.2-klein-4B
revision: ~
variant: ~

guidance_scale: 1.0
discrete_flow_shift: 3.1582
transformer_gradient_checkpointing: true
precomputed_embeddings_path: /home/wweligam/svd_v2/playground/null_prompt_embeddings_flux2_klein.pt

tracker_project_name: Motion
experiment_key: Flux2KleinLoRA

datasets:
  train:
    type: HuggingFaceDataset
    name: /depot/chan129/data/Deblur_MIOR/

    split: train
    trust_remote_code: true

    repeat: 20    
    num_proc: 32
    map_batch_size: 16

    use_shuffle: true
    gt_key: gt
    lq_key: blur
    
    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      crop_random:
        h: 512
        w: 512
      normalize:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

  val:
    type: HuggingFaceDataset
    name: /depot/chan129/data/Deblur_MIOR/
    split: validation
    trust_remote_code: true
    
    use_shuffle: false
    gt_key: gt
    lq_key: blur
    
    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      crop: 
        h: 512
        w: 512
      normalize:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

path:
  root: /scratch/gilbreth/wweligam/experiments
  logging_dir: logs
  resume_from_path: ~
  resume_from_checkpoint: ~

train:
  lora_rank: 128
  lora_alpha: 16
  lora_dropout: 0.0
  # lora_target_modules: [to_q, to_k, to_v, to_out.0, proj_out, ff.net, context_embedder, x_embedder]

  optim:
    type: adamw
    scale_lr: false
    use_8bit_adam: false
    learning_rate: !!float 5e-6
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: !!float 1e-8
    max_grad_norm: 1.0

  scheduler:
    type: constant
    lr_warmup_steps: 500
    lr_num_cycles: 1
    lr_power: 1.0

  gradient_accumulation_steps: 1
  num_train_epochs: 10
  batch_size: 4

  max_train_steps: 50000
  validation_steps: 2000
  checkpointing_steps: 5000
  checkpoints_total_limit: 3

  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 4

val:
  save_images: true
  use_cpu_offload: true
  num_inference_steps: 50
  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 4
  batch_size: 1
  max_val_steps: 5

  metrics:
    psnr:
      crop: 30
    mse:
      crop: 30
