name: DeepLens
model_type: DeepLensArray_model
is_train: true
report_to: comet_ml
push_to_hub: false
num_gpu: 8
seed: 10
mixed_precision: !!str no
allow_tf32: false
tracker_project_name: DeepLens
experiment_key: DeepLensArrayZoom

deeplens:
  array_size: [1, 1]  # cols, rows
  array_spacing: [!!float 0e-6, !!float 0e-6] # col, row spacing
  lens_file: "/depot/chan129/users/harshana/svd_v2/checkpoints/MetaZoom/metazoom2.json" 
  single_wavelength: true

  wavelength_set_m: [ !!float 550e-9] #[!!float 450e-9, !!float 550e-9, !!float 650e-9]  # B G R
  
  out_distance_m: !!float 2.5e-3

  fov: 6

  ps_locs:
    # - [-400e-6,-400e-6] # no Z value because we have variable depth
    # - [-400e-6, 0.0]
    # - [-400e-6, 400e-6]
    # - [0.0,-400e-6]
    - [0.0, 0.0]
    # - [0.0, 400e-6]
    # - [400e-6,-400e-6]
    # - [400e-6, 0.0]
    # - [400e-6, 400e-6]

  depth_min: !!float 1
  depth_max: !!float 1
  
  
datasets:
  train:
    type: DummyDataset
    size: 1024
    use_shuffle: true
    
  val:
    type: DummyDataset
    size: 1
    use_shuffle: true
    
# network structures
network:
  
# path
path:
  root: /scratch/gilbreth/wweligam/experiments
  logging_dir: logs
  resume_from_path: ~ # /scratch/gilbreth/wweligam/experiments/test/DeepLensArrayDepth 2025 10 05 21.20.39/
  resume_from_checkpoint: ~ #latest

# training settings
train:
  optimize_shape_param: true  # optimize MS shape parameters?
  check_speed: false
  
  optim:
    scale_lr: false
    use_8bit_adam: false
    learning_rate: !!float 2e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: !!float 1e-8
    max_grad_norm: 1.0

  scheduler:
    type: constant
    lr_warmup_steps: 500
    lr_num_cycles: 3
    lr_power: 1.0

  loss: 1*MSE
  gradient_accumulation_steps: 1
  num_train_epochs: 10
  batch_size: 4

  max_train_steps: 50000
  validation_steps: 100
  checkpointing_steps: 100
  checkpoints_total_limit: 2

  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 32

# validation settings
val:
  save_images: false
  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 8
  batch_size: 1

  metrics:
    psnr: # metric name, can be arbitrary
      crop: 30
    mse:
       crop: 30
