#!/bin/sh -l

#SBATCH -p a100-80gb
#SBATCH --mem 32G
#SBATCH -n32
#SBATCH -A stanchan
#SBATCH --nodes=1 --gpus-per-node=1 
#SBATCH --time=2-00:00:00
#SBATCH --job-name deepzoom


cd ../..
conda activate mypackages
accelerate launch trainer.py -opt /depot/chan129/users/harshana/svd_v2/checkpoints/MetaZoom/DeepLensArrayZoom.yml
