name: MetaZoom
model_type: Diffusion_MultiInput_model
is_train: true
report_to: comet_ml
push_to_hub: true
num_gpu: 8
seed: 10
mixed_precision: !!str no
allow_tf32: false
pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
revision: ~
variant: ~
use_ema: false
image_resolution: [512, 512]
tracker_project_name: MetaZoom
experiment_key: DiffusionNew200Dataset
dataset_caching: false

datasets:
  train1:
    type: HuggingFaceDataset
    name: /depot/chan129/users/harshana/Datasets/MetaZoom_New_aligned/1x/
    split: train
    num_proc: 4
    map_batch_size: 16
    trust_remote_code: true

    use_shuffle: true
    num_worker_per_gpu: 4
    gt_key: gt
    lq_key: blur
    rf_key: refined

    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      rescale:
        factor: 0.5
      crop:
        h: 1024
        w: 1024
      select_channels:
        channels: [True, True, True]
      # identity:
      #   keys: [lq_key]
      #   keys_new: [refined]
      # apply_model:
      #   keys: [lq_key]
      #   keys_new: [refined]
      #   model_name: Restormer_arch
      #   model_path: /scratch/gilbreth/wweligam/experiments/SVD/RestormerRealColor 2025 03 03 12.48.38/Restormer_arch_1/

  train2:
    type: HuggingFaceDataset
    name: /depot/chan129/users/harshana/Datasets/MetaZoom_New_aligned/5x/
    split: train
    num_proc: 4
    map_batch_size: 16
    trust_remote_code: true

    use_shuffle: true
    num_worker_per_gpu: 4
    gt_key: gt
    lq_key: blur
    rf_key: refined

    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      rescale:
        factor: 0.5
      crop:
        h: 1024
        w: 1024
      grayscale:
      # select_channels:
      #  keys: [gt]  # blur has only 1 channel
      #  channels: [False, True, False]
      # identity:
      #   keys: [lq_key]
      #   keys_new: [refined]
      # apply_model:
      #   keys: [lq_key]
      #   keys_new: [refined]
      #   model_name: Restormer_arch
      #   model_path: /scratch/gilbreth/wweligam/experiments/SVD/RestormerRealMono 2025 03 03 12.50.50/Restormer_arch_1/

  val1:
    type: HuggingFaceDataset
    name: /depot/chan129/users/harshana/Datasets/MetaZoom_New_aligned/1x/
    split: validation
    num_proc: 4
    trust_remote_code: true

    use_shuffle: false
    gt_key: gt
    lq_key: blur
    rf_key: refined
    
    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      rescale:
        factor: 0.5
      crop:
        h: 1024
        w: 1024
      select_channels:
       channels: [True, True, True]
      # identity:
      #   keys: [lq_key]
      #   keys_new: [refined]
      # apply_model:
      #   keys: [lq_key]
      #   keys_new: [refined]
      #   model_name: Restormer_arch
      #   model_path: /scratch/gilbreth/wweligam/experiments/SVD/RestormerRealColor 2025 03 03 12.48.38/Restormer_arch_1/

  val2:
    type: HuggingFaceDataset
    name: /depot/chan129/users/harshana/Datasets/MetaZoom_New_aligned/5x/
    split: validation
    num_proc: 4
    trust_remote_code: true

    use_shuffle: false
    gt_key: gt
    lq_key: blur
    rf_key: refined
    
    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      rescale:
        factor: 0.5
      crop:
        h: 1024
        w: 1024
      grayscale:
      # select_channels:
      #  keys: [gt]  # blur has only 1 channel
      #  channels: [False, True, False]
      # identity:
      #   keys: [lq_key]
      #   keys_new: [refined]
      # apply_model:
      #   keys: [lq_key]
      #   keys_new: [refined]
      #   model_name: Restormer_arch
      #   model_path: /scratch/gilbreth/wweligam/experiments/SVD/RestormerRealMono 2025 03 03 12.50.50/Restormer_arch_1/

# network structures
network:

LKPN_network:
  type: LKPN
  input_channels: 4
  k: 5
  time_emb_dim: 256

# path
path:
  root: /scratch/gilbreth/wweligam/experiments
  logging_dir: logs
  resume_from_path: ~ #/scratch/gilbreth/wweligam/experiments/SVD/DiffusionMetaZoomNew 2025 05 21 22.44.24/
  resume_from_checkpoint: ~ #latest

# training settings
train:
  optim:
    scale_lr: false
    use_8bit_adam: false
    learning_rate: !!float 1e-5
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: !!float 1e-8
    max_grad_norm: 1.0

  scheduler:
    type: cosine_with_restarts
    lr_warmup_steps: 500
    lr_num_cycles: 10
    lr_power: 1.0

  loss: 1*MSE
  gradient_accumulation_steps: 1
  num_train_epochs: 10
  batch_size: 1

  max_train_steps: 500000
  validation_steps: 1000
  checkpointing_steps: 5000
  checkpoints_total_limit: 2

  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 4

# validation settings
val:
  save_images: true
  batch_size: 1

  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 4

  use_1_as_start: false
  use_2_as_start: false

  metrics:
    psnr:
      crop: 30
    mse:
       crop: 30
