name: SVD
model_type: Simple2Dataset_model
is_train: true
report_to: comet_ml
push_to_hub: true
num_gpu: 8
seed: 10
mixed_precision: !!str no
allow_tf32: false
tracker_project_name: SVD_Synthetic
experiment_key: UnetSyntheticDeeplensOnline
dataset_caching: true

datasets:
  train1:
    type: DeepLensDataset
    gt_dataset_path: /depot/chan129/users/harshana/Datasets/Deconvolution/hybrid_Flickr2k_gt_v2/
    gt_dataset_file_pattern: !!str \*
    gt_key: gt
    lq_key: blur
    data_percent: [0, 99]
    num_proc: 4
    num_worker_per_gpu: 0
    lens_path: /depot/chan129/users/harshana/svd_v2/lenses/cooke40_inferior.json
    sensor_res: [1024, 1024]

    common_transforms_keys: [gt]
    transforms:
      to_tensor:
      select_channels:
        channels: [True, True, True, False]
      crop:
        h: 1024
        w: 1024
      rescale:
        factor: 1
      normalize:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
        
  train2:
    type: DeepLensDataset
    gt_dataset_path: /depot/chan129/users/harshana/Datasets/Deconvolution/hybrid_Flickr2k_gt_v2/
    gt_dataset_file_pattern: !!str \*
    gt_key: gt
    lq_key: blur
    data_percent: [0, 99]
    num_proc: 4
    num_worker_per_gpu: 0
    lens_path: /depot/chan129/users/harshana/svd_v2/lenses/thorlabs/acl12708u.json
    sensor_res: [1024, 1024]

    common_transforms_keys: [gt]
    transforms:
      to_tensor:
      select_channels:
        channels: [False, True, False, False]
      crop:
        h: 1024
        w: 1024
      rescale:
        factor: 1
      normalize:
        mean: [0.5]
        std: [0.5]

  val1:
    type: DeepLensDataset
    gt_dataset_path: /depot/chan129/users/harshana/Datasets/Deconvolution/hybrid_Flickr2k_gt_v2/
    gt_dataset_file_pattern: !!str \*
    gt_key: gt
    lq_key: blur
    data_percent: [99, 99.2]
    num_proc: 4
    num_worker_per_gpu: 0
    lens_path: /depot/chan129/users/harshana/svd_v2/lenses/cooke40_inferior.json
    sensor_res: [1024, 1024]

    common_transforms_keys: [gt]
    transforms:
      to_tensor:
      select_channels:
        channels: [True, True, True, False]
      crop:
        h: 1024
        w: 1024
      rescale:
        factor: 1
      normalize:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
        
  val2:
    type: DeepLensDataset
    gt_dataset_path: /depot/chan129/users/harshana/Datasets/Deconvolution/hybrid_Flickr2k_gt_v2/
    gt_dataset_file_pattern: !!str \*
    gt_key: gt
    lq_key: blur
    data_percent: [99, 99.2]
    num_proc: 4
    num_worker_per_gpu: 0
    lens_path: /depot/chan129/users/harshana/svd_v2/lenses/thorlabs/acl12708u.json
    sensor_res: [1024, 1024]

    common_transforms_keys: [gt]
    transforms:
      to_tensor:
      select_channels:
        channels: [False, True, False, False]
      crop:
        h: 1024
        w: 1024
      rescale:
        factor: 1
      normalize:
        mean: [0.5]
        std: [0.5]

# # network structures
# network:
#   type: Unet
#   in_channels: 4
#   out_channels: 3
#   attention_head_dim: 8
#   down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
#   up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"]
#   block_out_channels: [224, 448, 672, 896]

# network structures
network:
  type: UnetTM
  in_channels: 4
  out_channels: 3
  n_features: 16

# path
path:
  root: /scratch/gilbreth/wweligam/experiments
  logging_dir: logs
  resume_from_path: ~
  resume_from_checkpoint: ~

# training settings
train:
  optim:
    scale_lr: false
    use_8bit_adam: false
    learning_rate: !!float 2e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: !!float 1e-8
    max_grad_norm: 1.0

  scheduler:
    type: cosine_with_restarts
    lr_warmup_steps: 500
    lr_num_cycles: 3
    lr_power: 1.0

  loss: 1*MSE
  gradient_accumulation_steps: 1
  num_train_epochs: 10
  batch_size: 1

  max_train_steps: 50000
  validation_steps: 1000
  checkpointing_steps: 1000
  checkpoints_total_limit: 2

  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 8

# validation settings
val:
  save_images: true
  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 16
  batch_size: 1

  metrics:
    psnr: # metric name, can be arbitrary
      crop: 30
    mse:
       crop: 30
