#!/bin/sh -l
# FILENAME:  sjob1

#SBATCH -p a100-80gb
#SBATCH --mem 32G
#SBATCH -n32
#SBATCH -A stanchan
#SBATCH --nodes=1 --gpus-per-node=1 
#SBATCH --time=1-00:00:00
#SBATCH --job-name firstlayer-e2e


cd ..
conda activate mypackages
accelerate launch trainer.py -opt ./checkpoints/DepthEstimation/DFlatArrayDepthONN_e2e_kitti.yml
