name: SVD
model_type: DFlatArrayClassifier_model
is_train: true
report_to: comet_ml
push_to_hub: false
num_gpu: 8
seed: 10
mixed_precision: !!str no
allow_tf32: false
tracker_project_name: Dflat
experiment_key: DFlatArrayClassifier

dflat:
  array_size: [4, 4]
  array_spacing: [!!float 4000e-6, !!float 4000e-6]
  downscale_factor: [1, 1]
  h: 112
  w: 112
  in_dx_m: [!!float 3000e-9, !!float 3000e-9]
  out_dx_m: [!!float 5000e-9, !!float 5000e-9]

  wavelength_set_m: [!!float 400e-9, !!float 550e-9, !!float 700e-9]
  
  out_distance_m: !!float 1e-2
  initialization:
    type: focusing_lens
    depth_set_m: [!!float 1e-2, !!float 1e-2, !!float 1e-2]
    fshift_set_m: [[!!float 0.0, !!float 0.0],[!!float 0.0, !!float 0.0],[!!float 0.0, !!float 0.0]]
  model_name: Nanocylinders_TiO2_U300H600
  ps_locs: 
    loc0: [-400e-6,-400e-6] # no Z value because we have varianble depth
    loc1: [-400e-6, 0.0]
    loc2: [-400e-6, 400e-6]
    loc3: [0.0,-400e-6]
    loc4: [0.0, 0.0]
    loc5: [0.0, 400e-6]
    loc6: [400e-6,-400e-6]
    loc7: [400e-6, 0.0]
    loc8: [400e-6, 400e-6]
  ps_loc_z: !!float 10e-3
  
  
datasets:
  train:
    type: HuggingFaceDataset
    name: ylecun/mnist
    split: train
    # skip_cache: true

    use_shuffle: true
    num_worker_per_gpu: 4
    gt_key: image
    lq_key: sensor
    label_key: label

    common_transforms_keys: [image]
    transforms:
      to_tensor:
      rescale:
        factor: 4
      # select_channels:
      #  channels: [False, True, False]
      poisson_noise:
        peak: 1000
        peak_dc: 50
      gaussian_noise:
        max_sigma: 0.02
        sigma_dc: 0.005
        mu: 0

  val:
    type: HuggingFaceDataset
    name: ylecun/mnist
    split: test
    # skip_cache: true

    use_shuffle: false
    gt_key: image
    lq_key: sensor
    label_key: label
    
    common_transforms_keys: [image]
    transforms:
      to_tensor:
      rescale:
        factor: 4
      # select_channels:
      #  channels: [False, True, False]
      # poisson_noise:
      #   keys: [lq_key]
      #   peak: 1000
      #   peak_dc: 50
      # gaussian_noise:
      #   keys: [lq_key]
      #   max_sigma: 0.02
      #   sigma_dc: 0.005
      #   mu: 0
      
# network structures
network:
  type: MSArrayClassifier
  image_shape: [28, 28]
  n_classes: 10
  img_channel: 3
  width: 32


# path
path:
  root: /scratch/gilbreth/wweligam/experiments
  logging_dir: logs
  resume_from_path: /scratch/gilbreth/wweligam/FinalModels/StructureDeblur/NAFNetRealMono 2025 02 07 02.21.30/
  resume_from_checkpoint: ~

# training settings
train:
  optim:
    scale_lr: false
    use_8bit_adam: false
    learning_rate: !!float 2e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: !!float 1e-8
    max_grad_norm: 1.0

  scheduler:
    type: cosine_with_restarts
    lr_warmup_steps: 500
    lr_num_cycles: 3
    lr_power: 1.0

  loss: 1*MSE
  gradient_accumulation_steps: 1
  num_train_epochs: 10
  batch_size: 1

  max_train_steps: 50000
  validation_steps: 1000
  checkpointing_steps: 1000
  checkpoints_total_limit: 2

  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 32

# validation settings
val:
  save_images: false
  max_images: 10
  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 8
  batch_size: 32

  metrics:
    mse:
      crop: ~
    argmax:
      crop: ~
    