name: SVD
model_type: MetaDepthPhase2_model
is_train: true
report_to: comet_ml
push_to_hub: true
num_gpu: 8
seed: 10
mixed_precision: !!str no
allow_tf32: false
tracker_project_name: MetaDepth
experiment_key: MetaDepthPhase2
image_size: [64, 64]

tracker_kwargs:
  comet_ml:
    online: true
    
# network structures
network:
  type: UnetTM
  in_channels: 1
  out_channels: 2
  n_features: 16
# network:
#   type: Unet
#   in_channels: 1
#   out_channels: 2
#   attention_head_dim: 8
#   down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
#   up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"]
#   block_out_channels: [224, 448, 672, 896]

datasets:
  train:
    type: HuggingFaceDataset
    name: /depot/chan129/users/harshana/Datasets/SUNRGBD/kv2/kinect2data/
    split: train
    trust_remote_code: true

    use_shuffle: true
    num_worker_per_gpu: 4
    gt_key: gt
    lq_key: blur

    common_transforms_keys: [image, depth]
    transforms:
      to_tensor:
      select_channels:
       channels: [False, True, False]
      resize:
        h: 64
        w: 64

  val:
    type: HuggingFaceDataset
    name: /depot/chan129/users/harshana/Datasets/SUNRGBD/kv2/kinect2data/
    split: validation
    trust_remote_code: true
    
    use_shuffle: false
    gt_key: gt
    lq_key: blur
    
    common_transforms_keys: [image, depth]
    transforms:
      to_tensor:
      select_channels:
       channels: [False, True, False]
      resize:
        h: 64
        w: 64


# path
path:
  root: /scratch/gilbreth/wweligam/experiments
  logging_dir: logs
  resume_from_path: ~
  resume_from_checkpoint: ~

# training settings
train:
  optimize_shape_param: true  # optimize MS shape parameters?

  optim:
    scale_lr: false
    use_8bit_adam: false
    learning_rate: !!float 2e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: !!float 1e-8
    max_grad_norm: 1.0

  scheduler:
    type: cosine_with_restarts
    lr_warmup_steps: 500
    lr_num_cycles: 3
    lr_power: 1.0

  loss: 1*MSE
  gradient_accumulation_steps: 1
  num_train_epochs: 10
  batch_size: 1

  max_train_steps: 50000
  validation_steps: 1000
  checkpointing_steps: 1000
  checkpoints_total_limit: 2

  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 32

# validation settings
val:
  save_images: false
  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 8
  batch_size: 1

  metrics:
    psnr: # metric name, can be arbitrary
      crop: 30
    mse:
       crop: 30
