name: DeepLens
model_type: DeepLensArrayE2E_model
is_train: true
report_to: comet_ml
push_to_hub: false
num_gpu: 8
seed: 10
mixed_precision: !!str no
allow_tf32: false
tracker_project_name: DeepLens
experiment_key: DeepLensArrayDepthE2E

deeplens:
  array_size: [3, 3]  # cols, rows
  array_spacing: [!!float 0e-6, !!float 0e-6] # col, row spacing
  lens_file: "/depot/chan129/users/harshana/svd_v2/checkpoints/DepthEstimation/a489_doe_ours.json"
  single_wavelength: true

  wavelength_set_m: [ !!float 550e-9] #[!!float 450e-9, !!float 550e-9, !!float 650e-9]  # B G R
  
  out_distance_m: !!float 2.5e-3
   
  depth_levels: 4

  ps_locs:
    # - [-400e-6,-400e-6] # no Z value because we have variable depth
    # - [-400e-6, 0.0]
    # - [-400e-6, 400e-6]
    # - [0.0,-400e-6]
    - [0.0, 0.0]
    # - [0.0, 400e-6]
    # - [400e-6,-400e-6]
    # - [400e-6, 0.0]
    # - [400e-6, 400e-6]

  depth_min: !!float 10e-3
  depth_max: !!float 1000e-3
  
  
datasets:
  train1:
    type: HuggingFaceDataset
    name: harshana95/ForegroundDataset
    split: train
    trust_remote_code: true

    use_shuffle: true
    num_worker_per_gpu: 4
    gt_key: gt
    lq_key: blur

    common_transforms_keys: [foreground, mask]
    transforms:
      to_tensor:
      select_channels:
       channels: [True, True, True, False]
      crop:
        h: 128
        w: 128
      rescale:
        factor: 4
      poisson_noise:
        peak: 1000
        peak_dc: 50
      gaussian_noise:
        max_sigma: 0.02
        sigma_dc: 0.005
        mu: 0
  
  train2:
    type: HuggingFaceDataset
    name: harshana95/BackgroundDataset
    split: train
    trust_remote_code: true

    use_shuffle: true
    num_worker_per_gpu: 4
    gt_key: gt
    lq_key: blur

    common_transforms_keys: [background]
    transforms:
      to_tensor:
      select_channels:
       channels: [True, True, True, False]
      crop:
        h: 128
        w: 128
      rescale:
        factor: 4
      poisson_noise:
        peak: 1000
        peak_dc: 50
      gaussian_noise:
        max_sigma: 0.02
        sigma_dc: 0.005
        mu: 0

  val1:
    type: HuggingFaceDataset
    name: harshana95/ForegroundDataset
    split: validation
    trust_remote_code: true
    
    use_shuffle: false
    gt_key: gt
    lq_key: blur
    
    common_transforms_keys: [foreground, mask]
    transforms:
      to_tensor:
      select_channels:
       channels: [True, True, True, False]
      crop:
        h: 128
        w: 128
      rescale:
        factor: 4
      poisson_noise:
        peak: 1000
        peak_dc: 50
      gaussian_noise:
        max_sigma: 0.02
        sigma_dc: 0.005
        mu: 0

  val2:
    type: HuggingFaceDataset
    name: harshana95/BackgroundDataset
    split: validation
    trust_remote_code: true
    
    use_shuffle: false
    gt_key: gt
    lq_key: blur
    
    common_transforms_keys: [background]
    transforms:
      to_tensor:
      select_channels:
       channels: [True, True, True, False]
      crop:
        h: 128
        w: 128
      rescale:
        factor: 4
      poisson_noise:
        peak: 1000
        peak_dc: 50
      gaussian_noise:
        max_sigma: 0.02
        sigma_dc: 0.005
        mu: 0
      
# network structures
network:
  type: MSArrayIR
  img_channel: 3
  width: 96

# path
path:
  root: /scratch/gilbreth/wweligam/experiments
  logging_dir: logs
  resume_from_path: /scratch/gilbreth/wweligam/experiments/DeepLens/DeepLensArrayDepthE2E 2025 10 06 22.34.27/
  resume_from_checkpoint: latest

# training settings
train:
  optimize_shape_param: false  # optimize MS shape parameters?
  optimize_lens_param: false # optimize geolens parameters?
  check_speed: false
  
  optim:
    scale_lr: false
    use_8bit_adam: false
    learning_rate: !!float 5e-5
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: !!float 1e-8
    max_grad_norm: 1.0

  scheduler:
    type: constant
    lr_warmup_steps: 500
    lr_num_cycles: 3
    lr_power: 1.0

  loss: 1*MSE
  gradient_accumulation_steps: 1
  num_train_epochs: 10
  batch_size: 8

  max_train_steps: 100000
  validation_steps: 100
  checkpointing_steps: 100
  checkpoints_total_limit: 2

  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 32

# validation settings
val:
  save_images: false
  patched: false
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 8
  batch_size: 1

  metrics:
    psnr: # metric name, can be arbitrary
      crop: 30
    mse:
       crop: 30
