name: SVD_Synthetic
model_type: Simple2Dataset_model
is_train: true
report_to: comet_ml
push_to_hub: true
num_gpu: 8
seed: 10
mixed_precision: !!str no
allow_tf32: false
tracker_project_name: SVD_Synthetic
experiment_key: UnetSyntheticDeeplens

datasets:
  train1:
    type: HuggingFaceDataset
    name: harshana95/synthetic_hybrid_Flickr2k_gt_v2_deeplens_color_synthetic_color
    split: train
    num_proc: 4
    map_batch_size: 16

    use_shuffle: true
    num_worker_per_gpu: 4
    gt_key: gt
    lq_key: blur
    rf_key: refined

    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      crop:
        h: 1024
        w: 1024
      rescale:
        factor: 0.5
      select_channels:
        channels: [True, True, True]
      # identity:
      #   keys: [lq_key]
      #   keys_new: [refined]
      # apply_model:
      #   keys: [lq_key]
      #   keys_new: [refined]
      #   model_name: Restormer_arch
      #   model_path: /scratch/gilbreth/wweligam/experiments/SVD/RestormerRealColor 2025 03 03 12.48.38/Restormer_arch_1/

  train2:
    type: HuggingFaceDataset
    name: harshana95/synthetic_hybrid_Flickr2k_gt_v2_deeplens_synthetic_mono
    split: train
    num_proc: 4
    map_batch_size: 16

    use_shuffle: true
    num_worker_per_gpu: 4
    gt_key: gt
    lq_key: blur
    rf_key: refined

    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      crop:
        h: 1024
        w: 1024
      rescale:
        factor: 0.5
      select_channels:
       channels: [False, True, False]
      # identity:
      #   keys: [lq_key]
      #   keys_new: [refined]
      # apply_model:
      #   keys: [lq_key]
      #   keys_new: [refined]
      #   model_name: Restormer_arch
      #   model_path: /scratch/gilbreth/wweligam/experiments/SVD/RestormerRealMono 2025 03 03 12.50.50/Restormer_arch_1/

  val1:
    type: HuggingFaceDataset
    name: harshana95/synthetic_hybrid_Flickr2k_gt_v2_deeplens_color_synthetic_color
    split: validation
    num_proc: 4

    use_shuffle: false
    gt_key: gt
    lq_key: blur
    rf_key: refined
    
    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      crop:
        h: 1024
        w: 1024
      rescale:
        factor: 0.5
      select_channels:
       channels: [True, True, True]
      # identity:
      #   keys: [lq_key]
      #   keys_new: [refined]
      # apply_model:
      #   keys: [lq_key]
      #   keys_new: [refined]
      #   model_name: Restormer_arch
      #   model_path: /scratch/gilbreth/wweligam/experiments/SVD/RestormerRealColor 2025 03 03 12.48.38/Restormer_arch_1/

  val2:
    type: HuggingFaceDataset
    name: harshana95/synthetic_hybrid_Flickr2k_gt_v2_deeplens_synthetic_mono
    split: validation
    num_proc: 4

    use_shuffle: false
    gt_key: gt
    lq_key: blur
    rf_key: refined
    
    common_transforms_keys: [gt, blur]
    transforms:
      to_tensor:
      crop:
        h: 1024
        w: 1024
      rescale:
        factor: 0.5
      select_channels:
       channels: [False, True, False]
      # identity:
      #   keys: [lq_key]
      #   keys_new: [refined]
      # apply_model:
      #   keys: [lq_key]
      #   keys_new: [refined]
      #   model_name: Restormer_arch
      #   model_path: /scratch/gilbreth/wweligam/experiments/SVD/RestormerRealMono 2025 03 03 12.50.50/Restormer_arch_1/

# network structures
network:
  type: Unet
  in_channels: 4
  out_channels: 3
  attention_head_dim: 8
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"]
  block_out_channels: [224, 448, 672, 896]


# path
path:
  root: /scratch/gilbreth/wweligam/experiments
  logging_dir: logs
  resume_from_path: ~ # /scratch/gilbreth/wweligam/experiments/SVD/UnetSyntheticDeeplens 2025 08 29 11.09.16/
  resume_from_checkpoint: ~ # latest

# training settings
train:
  optim:
    scale_lr: false
    use_8bit_adam: false
    learning_rate: !!float 2e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: !!float 1e-8
    max_grad_norm: 1.0

  scheduler:
    type: cosine_with_restarts
    lr_warmup_steps: 500
    lr_num_cycles: 3
    lr_power: 1.0

  loss: 1*MSE
  gradient_accumulation_steps: 1
  num_train_epochs: 10
  batch_size: 1

  max_train_steps: 50000
  validation_steps: 250
  checkpointing_steps: 100
  checkpoints_total_limit: 2

  patched: true
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 8

# validation settings
val:
  save_images: true
  patched: true
  patch_size_h: 256
  patch_size_w: 256
  patch_overlap: 0.2
  max_minibatch: 16
  batch_size: 1

  metrics:
    psnr: # metric name, can be arbitrary
      crop: 30
    mse:
       crop: 30
